# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

homepage:
  url:   /
  param: { module: inv, action: index }

legal:
  url:   /
  param: { module: inv, action: index }

about:
  url:   /
  param: { module: inv, action: index }

download_manual:
  url:   /download/manual.:sf_format
  param: { module: inv, action: DownloadManual, sf_format: pdf}


# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

sf_guard_signin:
  url:   /login
  param: { module: sfGuardAuth, action: signin }

sf_guard_signout:
  url:   /logout
  param: { module: sfGuardAuth, action: signout }

sf_guard_password:
  url:   /request_password
  param: { module: sfGuardAuth, action: password }

  #
change_password:
  url:              /changepassword
  param:            { module: inv, action: ChangePasswordShow }
change_password_do:
  url:              /dochangepassword
  param:            { module: inv, action: ChangePassword }

recover_password:
  url:              /recoverpassword
  param:            { module: inv, action: RecoverPasswordShow }
recover_password_do:
  url:              /dorecoverpassword
  param:            { module: inv, action: RecoverPassword }

